swagger: 2.0
info:
  title: Test API
  description: 测试的
  version: 0.0.1
host: localhost:8088
schemes: 
  - http
basePath: /apis
produces:
  - application/json
paths:
  /api/{id}:
    get:
      title: 1

  /v:
    get:
      title: a

